### ISSUE TITLE
Path attribute in context file unnecessary

### ISSUE THREAD

**Issue by mystygage** [tomcatplugin/tomcatplugin#33] opened 2021-03-24 11:40 UTC
The Tomcat plugin is configured with context declaration mode _context files_. I have a project configured with `app`. This creates a XML file `app.xml` with the following content:
```
<Context path="/app" reloadable="false" docBase="/Users/user/Projects/git/app-folder" workDir="/Users/user/Projects/git/app-folder/work" />
```

At least for Tomcat 9 the path attribute in context files is unnecessary. Tomcat starts with this warning:
```
WARNING: The path attribute with value [/app] in deployment descriptor [tomcat/conf/Catalina/localhost/app.xml] has been ignored
```

Omitting the path attribute removes the warning.

**Comment by markuskeunecke** [comment] 2022-07-28 19:35
Duplicate of #35. Closing this one as in #35 is more discussion.

**Closed as not planned by markuskeunecke** 2022-07-28 19:35 UTC
Labels: duplicate
